# Generated by Django 4.2.14 on 2024-08-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_pendingorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingOrder',
        ),
    ]
