# Generated by Django 4.2.14 on 2024-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='matched_quantity',
        ),
    ]
