# Generated by Django 4.2.14 on 2024-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_order_cancelled_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='matched_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
