# Generated by Django 4.2.14 on 2024-08-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_closedevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEvent',
        ),
    ]
