# Generated by Django 4.2.14 on 2024-08-15 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0012_delete_closedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancel_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('settled_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.settledevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
